//screen constants

// export const KEY_BOTTOM_TAB_NAVIGATION = 'bottomTabNavigator'
export const SCREEN_LOGIN = 'loginScreen'
export const SCREEN_SINGUP = 'signupScreen'
export const SCREEN_HOME = 'homeScreen'
export const SCREEN_SPALSH = 'splashScreen'
export const SCREEN_SEARCH = 'searchScreen'
export const SCREEN_CART = 'cartScreen'
export const SCREEN_NOTIFICATION = 'notificationScreen'
export const SCREEN_PROFILE = 'profileScreen'
export const SCREEN_BOTTOMTABNAVIGATION = 'bottomTabScreen'
export const SCREEN_ADD_ADDRESS = 'addAddressScreen'
export const SCREEN_ORDER = 'orderScreen'
export const SCREEN_OFFERS = 'offersScreen'
export const SCREEN_SUCCESS = 'successScreen'
export const SCREEN_FAILED = 'failedScreen'